# Generated by Django 5.0.2 on 2024-03-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': (['-student_name'],), 'verbose_name': 'student'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studnet_age',
            new_name='student_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studnet_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studnet_name',
            new_name='student_name',
        ),
    ]
