# Generated by Django 5.0.2 on 2024-03-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=19)),
            ],
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('department',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('student_name',), 'verbose_name': 'student'},
        ),
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stapp.student', verbose_name='studentmarks')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stapp.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
